const actionTypes ={
    GET_USERS_REQUEST:"GET_USERS_REQUEST",
    GET_USERS_SUCCEEDED:"GET_USERS_SUCCEEDED",
    GET_USERS_FAILURE:"GET_USERS_FAILURE",
    DELETE_USER_REQUEST:"DELETE_USER_REQUEST",
    DELETE_USER_SUCCEEDED:"DELETE_USER_SUCCEEDED",
    DELETE_USERS_FAILURE:"DELETE_USERS_FAILURE"
}
export default actionTypes;