const actionTypes= {
    LOAD_PRODUCTS:"LOAD_PRODUCTS",
    PRODUCTS_FETCH_SUCCEEDED:"PRODUCTS_FETCH_SUCCEEDED",
    ADD_TO_CART:"ADD_TO_CART", 
    CHECK_OUT_REQUEST:"CHECK_OUT_REQUEST",
    CHECK_OUT_SUCCEDDED:"CHECK_OUT_SUCCEEDED",
    CHECK_OUT_FAILURE:"CHECK_OUT_FAILURE"
}
export default actionTypes