const actionTypes= {
    LOAD_PRODUCTS:"LOAD_PRODUCTS",
    PRODUCTS_FETCH_SUCCEEDED:"PRODUCTS_FETCH_SUCCEEDED",
    ADD_TO_CART_REQUEST:"ADD_TO_CART_REQUEST", 
    ADD_TO_CART_SUCCEEDED:"ADD_TO_CART_SUCCEEDED", 
    ADD_TO_CART_FAILURE:"ADD_TO_CART_FAILURE", 
    CHECK_OUT_REQUEST:"CHECK_OUT_REQUEST",
    CHECK_OUT_SUCCEDDED:"CHECK_OUT_SUCCEEDED",
    CHECK_OUT_FAILURE:"CHECK_OUT_FAILURE", 
    SEARCH_REQUEST:"SEARCH_REQUEST",
    SEARCH_REQUEST_SUCCEEDED:"SEARCH_REQUEST_SUCCEED",
    SEARCH_REQUEST_FAILURE:"SEARCH_REQUEST_FAILURE",
    CHANGE_PAGE:"CHANGE_PAGA",
    CHANGE_PAGE_SUCCEEDED:"CHANGE_PAGE_SUCCEEDED",
    CHANGE_PAGE_FAILURE:"CHANGE_PAGE_FAILURE",
}
export default actionTypes