const actionTypes = {
    LOGIN:"LOGIN",
    LOGIN_SUCCEEDED:"LOGIN_SUCCEEDED",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    LOGIN_AUTH_FAILURE:"LOGIN_AUTH_FAILURE",
    GET_USERSLIST_REQUEST:"GET_USERSLIST_REQUEST",
    GET_USERSLIST_SUCCEEDED:"GET_USERSLIST_SUCCEEDED",
    GET_USERSLIST_FAILURE:"GET_USERSLIST_SUCCEEDED"
}
export default actionTypes;